#!/usr/bin/env python3
"""Mirror the shipped scorer into an importable Python package for PyPI.

The scorer modules and pattern data are byte-pinned by mcp/scripts/sync_scorer.py
so the hosted Worker, the installed skill, and the published wheel all run the
same code. This script copies those exact bytes into packaging/zero_slop/ and
never edits them. CI runs it with --check so a pull request that touches the
scorer without regenerating the mirror fails.

    python3 tooling/build_pypi.py            # regenerate the mirror
    python3 tooling/build_pypi.py --check    # verify it is current (CI)

Layout matters. slopscore.py resolves its data as `__file__/../../data`, so the
mirror keeps the scripts/ and data/ pair one level below the package root. That
is why the wheel installs zero_slop/scripts/ rather than flattening the modules.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "packaging" / "zero_slop"

# Byte-identical to the sources pinned by mcp/scripts/sync_scorer.py. Adding a
# module here without adding it there would let the wheel and the Worker drift.
MODULES = ("slopscore.py", "register.py", "rerank.py", "safeio.py")
# Authored here rather than mirrored from the pinned set: the multi-file gate
# is the pre-commit and shell entry point and ships only in the wheel.
EXTRA_MODULES = ("gate.py",)
DATA = ("patterns.json", "learned.json")

PACKAGE_INIT = '''"""Zero Slop — score AI-sounding prose and check what a rewrite changed.

The scorer runs offline and uses only the Python standard library.

    from zero_slop import score_text, load_patterns

    data = load_patterns()
    score_text("We are thrilled to announce...", data)["ai_likelihood"]
"""

from zero_slop.scripts.slopscore import load_patterns, score_text

__all__ = ["load_patterns", "score_text", "__version__"]
__version__ = "{version}"
'''

SCRIPTS_INIT = '"""Byte-identical mirror of the shipped scorer. Generated by scripts/build_pypi.py."""\n'


def version() -> str:
    return str(json.loads((ROOT / "package.json").read_text())["version"])


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def planned() -> dict[Path, bytes]:
    """Every file the mirror should contain, as exact bytes."""
    files: dict[Path, bytes] = {
        PACKAGE / "__init__.py": PACKAGE_INIT.format(version=version()).encode(),
        PACKAGE / "scripts" / "__init__.py": SCRIPTS_INIT.encode(),
    }
    for name in MODULES:
        files[PACKAGE / "scripts" / name] = (ROOT / "scripts" / name).read_bytes()
    for name in EXTRA_MODULES:
        files[PACKAGE / "scripts" / name] = (ROOT / "tooling" / name).read_bytes()
    for name in DATA:
        files[PACKAGE / "data" / name] = (ROOT / "data" / name).read_bytes()
    return files


def write(files: dict[Path, bytes]) -> None:
    if PACKAGE.exists():
        shutil.rmtree(PACKAGE)
    for path, payload in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)


def check(files: dict[Path, bytes]) -> list[str]:
    problems: list[str] = []
    for path, payload in files.items():
        rel = path.relative_to(ROOT)
        if not path.exists():
            problems.append(f"missing {rel}")
        elif path.read_bytes() != payload:
            problems.append(f"stale {rel}")
    if PACKAGE.exists():
        for found in sorted(PACKAGE.rglob("*")):
            # Build output and bytecode caches are not part of the mirror.
            # `python3 -m build` drops egg-info here, and merely importing a
            # mirrored module writes __pycache__ beside it, which would
            # otherwise make the mirror look stale the moment it is exercised.
            if any(part.endswith(".egg-info") or part == "__pycache__"
                   for part in found.parts):
                continue
            if found.is_file() and found not in files:
                problems.append(f"unexpected {found.relative_to(ROOT)}")
    return problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the mirror matches the shipped scorer, and change nothing")
    args = parser.parse_args(argv)

    files = planned()
    if args.check:
        problems = check(files)
        if problems:
            print("The PyPI mirror is out of date. Run: python3 scripts/build_pypi.py",
                  file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            return 1
        print(f"packaging/zero_slop matches the shipped scorer ({len(files)} files)")
        return 0

    write(files)
    for name in MODULES:
        source = ROOT / "scripts" / name
        mirrored = PACKAGE / "scripts" / name
        assert digest(source) == digest(mirrored), name
    print(f"Wrote packaging/zero_slop ({len(files)} files) at version {version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
